name: Sync cdnfolder from private repo

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger from the Actions tab

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          node-version: '20'
          token: ${{ secrets.GH_PAT }}

      - name: Checkout private repository
        uses: actions/checkout@v3
        with:
          repository: imranmajeed473/phpcodes
          node-version: '20'
          token: ${{ secrets.GH_PAT }}
          path: private-repo # Specifies the directory to checkout the private repo

      - name: Copy cdnfolder
        run: |
          rsync -av --progress private-repo/cdnfolder/ cdnfolder/ --exclude .git --include='chromeinject.css' --include='chromeinject.js' --delete

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Sync cdnfolder from private repository" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/imranmajeed473/cdncodes.git HEAD:main
